# Generated by Django 3.1 on 2020-09-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafepages', '0004_auto_20200913_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='fname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='lname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
