# Generated by Django 3.1 on 2020-09-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafepages', '0005_auto_20200913_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
    ]
