# Generated by Django 3.1 on 2020-09-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafepages', '0006_subscribers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subscribers',
        ),
    ]
