# Generated by Django 3.1 on 2020-09-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafepages', '0007_delete_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
